server:
  port: 8989
cas:
  server-url-prefix: http://1.15.51.147/sign/authz/cas/
  server-login-url: http://1.15.51.147/sign/authz/cas/login
  client-host-url: http://localhost:8989/
  validation-type: cas
  #  拦截的URL地址
  authentication-url-patterns:
    - /test/index
    - /test/index1